name: Auto Flight Tracking

on:
  schedule:
    - cron: "0 */10 * * *"   # toutes les 10h
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest

    env:
      SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run tracking script
        env:
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
        run: python track.py

      - name: Commit data changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add data.json || true
          git commit -m "Auto update prices" || echo "No changes"
          git push || echo "No permission to push"
