name: Auto Tracking

on:
  schedule:
    - cron: "0 */10 * * *"   # toutes les 10 heures
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tracking script
        run: |
          python track.py

      - name: Commit updated data
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add data/routes.json
          git commit -m "Auto update" || echo "No changes"
          git push
